### ISSUE TITLE
Critical: Ream creates invalid Webpack config object

### ISSUE THREAD

**Issue by IlyaSemenov** [ream/ream#115]
With the latest deps, fresh Ream install in an empty project directory (according to https://ream.js.org/guide/introduction.html) can't even start due to a Webpack config error.

## Steps to reproduce

Create `Dockerfile`:

```dockerfile
FROM node:10

WORKDIR /test
RUN npm i ream && npx ream dev
```

run it:

```
docker build .
```

## Results

```
...
+ ream@3.2.8
added 876 packages from 451 contributors and audited 9124 packages in 36.408s
found 0 vulnerabilities

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.externals should be one of these:
   function | string | object { <key>: string | object | [non-empty string] | boolean } | RegExp | [function | string | object { <key>: string | object | [non-empty string] | boolean } | RegExp]
   -> Specify dependencies that shouldn't be resolved by webpack, but should become dependencies of the resulting bundle. The kind of the dependency depends on `output.libraryTarget`.
   Details:
    * configuration.externals should be an instance of function
      -> `function(context, request, callback(err, result))` The function is called on each dependency.
    * configuration.externals should be a string.
      -> An exact matched dependency becomes external. The same string is used as external dependency.
    * configuration.externals should be an object.
      -> If an dependency matches exactly a property of the object, the property value is used as dependency.
    * configuration.externals should be an instance of RegExp
      -> Every matched dependency becomes external.
    * configuration.externals[0] should be an instance of function
      -> `function(context, request, callback(err, result))` The function is called on each dependency.
    * configuration.externals[0] should be a string.
      -> An exact matched dependency becomes external. The same string is used as external dependency.
    * configuration.externals[0] should be an object.
      -> If an dependency matches exactly a property of the object, the property value is used as dependency.
    * configuration.externals[0] should be an instance of RegExp
      -> Every matched dependency becomes external.
    at webpack (/test/node_modules/webpack/lib/webpack.js:31:9)
    at createConfigs.map.config (/test/node_modules/ream/lib/index.js:149:47)
    at Array.map (<anonymous>)
    at Ream.createCompilers (/test/node_modules/ream/lib/index.js:149:33)
    at module.exports.api (/test/node_modules/ream/lib/utils/setupWebpackMiddlewares.js:4:48)
    at Ream.getServer (/test/node_modules/ream/lib/index.js:270:49)
```

---

Of course Docker is not required, I was just using it to 100% reliably isolate my environment.

**Comment by IlyaSemenov** [comment]
I think there are extra square brackets here: https://github.com/ream/ream/blob/9e368363ae19ce22443577698b68665ee528f9aa/lib/webpack/webpack.config.server.js#L25 but I'm not 100% sure.

**Comment by IlyaSemenov** [comment]
Until the fix is merged, the workaround is adding this to config:

```ts
chainWebpack (config) {
	const externals = config.get('externals')
	if (Array.isArray(externals) && externals.length === 1 && Array.isArray(externals[0])) {
		// Fix Ream bug, see https://github.com/ream/ream/issues/115
		config.externals(externals[0])
	}
}
```

Sometimes I wonder if I'm the only one using Ream? 🤔It seems to hit the middle ground between bloated Nuxt and boilerplate repetitive Vue SSR just perfectly. So sad it's not getting any traction.
