### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by brillout** [ream/ream#221]
Hi @egoist !

I wanted to try your framework but I got an error while building.

```shell
~/tmp/my-app (main*%) npm run build

> build
> ream build

ℹ Using config file: ream.config.ts                                                                                                                               10:20:47
ℹ Preparing Ream files                                                                                                                                            10:20:47
vite v2.0.5 building SSR bundle for production...
vite v2.0.5 building for production...
✓ 10 modules transformed.
[rollup-plugin-dynamic-import-variables] Unexpected token (4:9)
file: /home/romuuu/tmp/my-app/pages/_app.js:4:9

 ERROR  Unexpected token (4:9)                                                                                                                                    10:20:49

  at Object.pp$4.raise (node_modules/rollup/dist/shared/rollup.js:15574:13)
  at Object.pp.unexpected (node_modules/rollup/dist/shared/rollup.js:13266:8)
  at Object.pp$3.parseExprAtom (node_modules/rollup/dist/shared/rollup.js:14973:10)
  at Object.pp$3.parseExprSubscripts (node_modules/rollup/dist/shared/rollup.js:14776:19)
  at Object.pp$3.parseMaybeUnary (node_modules/rollup/dist/shared/rollup.js:14753:17)
  at Object.parseMaybeUnary (node_modules/rollup/dist/shared/rollup.js:19479:29)
  at Object.pp$3.parseExprOps (node_modules/rollup/dist/shared/rollup.js:14688:19)
  at Object.pp$3.parseMaybeConditional (node_modules/rollup/dist/shared/rollup.js:14671:19)
  at Object.pp$3.parseMaybeAssign (node_modules/rollup/dist/shared/rollup.js:14639:19)
  at Object.pp$3.parseExpression (node_modules/rollup/dist/shared/rollup.js:14605:19)

transforming (13) node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js > pages/_app.js:4:9: error: Unexpected "<"
    4 │   return <Component {...pageProps} />
      ╵          ^

 > pages/index.js:6:4: error: Unexpected "<"
    6 │     <div className={styles.container}>
      ╵     ^

transforming (15) node_modules/@vue/shared/dist/shared.esm-bundler.jsnpm ERR! code 1
```

Seems like JSX is not being transpiled.

Reproduction:
```shell
npx create-ream-app my-app
cd my-app/
npm install
npm run build
```

**Comment by egoist** [comment]
Yeah JSX is not yet supported by default, manually adding the vue jsx plugin via vite.config.ts might work tho.

**Comment by brillout** [comment]
Maybe it should be included in the boilerplate then
