### ISSUE TITLE
Cannot find module 'fs-promise'

### ISSUE THREAD

**Issue by evilemon** [ream/ream#25]
module.js:472
    throw err;
    ^

Error: Cannot find module 'fs-promise'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/evilemon/work/ream/lib/index.js:4:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

I encounter this problem in many examples,i wonder which verion of npm  or node?

**Comment by egoist** [comment]
node ≥ 6, npm ≥ 3

**Comment by evilemon** [comment]
node 7.7.1  npm 4.1.2

**Comment by egoist** [comment]
no idea how this would happen, it's listed in package.json anyway https://github.com/ream/ream/blob/dev/package.json#L77 maybe provide the steps to reproduce this?

**Comment by cannap** [comment]
@evilemon are you installed ream with global? i had some same issue with other package 

when yes: remove the global one and install ream in the project itself

**Comment by egoist** [comment]
@cannap I actually think it's ok to install ream globally.
