### ISSUE TITLE
cant install axios module not found 

### ISSUE THREAD

**Issue by cannap** [ream/ream#31]
:/  i have no idea whats wrong
```
error during render : /
{ Error: Cannot find module 'axios'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at r (C:\Users\marko\AppData\Roaming\nvm\v6.5.0\node_modules\ream\node_modules\vue-server-renderer\build.js:6964:16)
    at Object.<anonymous> (webpack:/external "axios":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap cada09c6e8c3112b4e53:25:0)
    at Object.<anonymous> (0.server-bundle.js:73:64)
    at __webpack_require__ (webpack:/webpack/bootstrap cada09c6e8c3112b4e53:25:0)
    at Object.<anonymous> (0.server-bundle.js:46:72)
    at __webpack_require__ (webpack:/webpack/bootstrap cada09c6e8c3112b4e53:25:0)
    at Object.exports.modules.Object.defineProperty.value (src/views/Home.vue:7:0)
    at __webpack_require__ (webpack:/webpack/bootstrap cada09c6e8c3112b4e53:25:0)
    at process._tickCallback (internal/process/next_tick.js:103:7) code: 'MODULE_NOT_FOUND' }
```
api.js 

```js
import axios from 'axios'
const api = 'http://localhost:8080/wprest/wp-json/wp/v2'

axios.defaults.baseURL = api
let wordpresService = {
  async getPosts() {
    const data = await axios.get('posts')
  
  }

}

export default wordpresService

```
home.vue
```js


<style lang="scss" type="text/scss">
    body {
        background: red;
    }
</style>

<template>
    <div class="greg"></div>
</template>

<script>
  import api  from '../services/api'
  //const api2 = 'http://localhost:8080/wprest/wp-json/wp/v2'
  export default {

    name: 'Home',

  }
</script>

```

package.json
```

{
  "name": "restshop",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "ream build",
    "start": "ream start",
    "dev": "ream dev"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-plugin-component": "^0.9.1",
    "node-sass": "^4.5.2",
    "sass-loader": "^6.0.3"
  },
  "dependencies": {
    "axios": "^0.16.0",
    "vue": "^2.2.6",
    "vue-router": "^2.3.1"
  }
}
```

/e i tried the example asyc-data still not working i use windows 10
node 6.5.0 lates  ream beta

**Comment by FrancosLab** [comment]
You sure you ran "npm install" or "yarn install"?

**Comment by cannap** [comment]
@FrancosLab  sure :D

**Comment by egoist** [comment]
Hmm, it works for me (https://glitch.com/edit/#!/ream-async-data)

**Comment by cannap** [comment]
Hi i i will try again later atm i have no time but i will give report

**Comment by cannap** [comment]
i made a video https://www.youtube.com/watch?v=4ar80J9Bf4o&feature=youtu.be

**Comment by cannap** [comment]
ah i think i know the problem lol i installed ream global -.- this is why ream looks in the wrong folder omg
