### ISSUE TITLE
Server Crash when exporting vuex store (vue-meta)

### ISSUE THREAD

**Issue by cannap** [ream/ream#33]
```js
import Vue from 'vue'
import Router from 'vue-router'
import Home from './views/Home.vue'
import Vuex from 'vuex'
//import modules from './vuex/modules'

Vue.use(Router)
Vue.use(Vuex)
const router = new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      component: Home
    }
  ]
})

const store = new Vuex.Store({

})

export default {router,store}
```

Error on Server:
```
:\wpresttheme\node_modules\vue-meta\lib\vue-meta.js:824
    var htmlTag = document.getElementsByTagName('html')[0];
                                                       ^

ReferenceError: document is not defined
    at updateClientMetaInfo (C:\wpresttheme\node_modules\vue-meta\lib\vue-meta.js:824:56)
    at Vue$2.refresh (C:\wpresttheme\node_modules\vue-meta\lib\vue-meta.js:885:35)
```

  "version": "1.0.0-beta.9",

it works the first time but when i press f5 then i get this error 

**/e**

looks like vue-meta has a bug in 0.5.6 https://github.com/declandewet/vue-meta/issues/82

**Comment by jazoom** [comment]
Yup, it appears to be a vue-meta bug.
