### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by ppot** [ream/ream#52]
I used the `custom-koa-server` and can't run it always getting the error: 

```
remote:        ERROR in ./~/ream/app/App.vue
remote:        Module build failed: Error: Cannot find module 'lru-cache'
remote:        at Function.Module._resolveFilename (module.js:470:15)
remote:        at Function.Module._load (module.js:418:25)
remote:        at Module.require (module.js:498:17)
remote:        at require (internal/module.js:20:19)
remote:        at Object.<anonymous> (/tmp/build_55aad07f5c932805d0e2761b00b04633/node_modules/vue-loader/lib/parser.js:2:13)
remote:        at Module._compile (module.js:571:32)
```

**Comment by ppot** [comment]
solved. Missed in package.json
```
  “engines”: {
    “node”: “7.10.0”,
    “npm”: “4.2.0”
  },
```
