### ISSUE TITLE
Unhandled error during execution of setup function

### ISSUE THREAD

**Issue by nblthree** [ream/ream#90]
Cloning ream
run `yarn`
run `yarn build`
run `yarn link` in ream package
run `yarn link ream` in website
run `yarn dev`

I get 

Preparing Ream files

√ Client
  Compiled successfully in 1.09m

√ Server
  Compiled successfully in 1.07m

```
> http://localhost:3000
You are running a development build of Vue.
Make sure to use the production build (*.prod.js) when deploying for production.
You are running the esm-bundler build of Vue. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle. See http://link.vuejs.org/feature-flags for more details.
[Vue warn]: Unhandled error during execution of setup function
  at <RouterView>
server error TypeError: Cannot read property 'parent' of null
    at warnDeprecatedUsage (C:\Users\Nabil\Project\ream\website\.ream\server\main.js:12972:33)
    at setup (C:\Users\Nabil\Project\ream\website\.ream\server\main.js:12915:20)
    at callWithErrorHandling (C:\Users\Nabil\Project\ream\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:156:22)
    at setupStatefulComponent (C:\Users\Nabil\Project\ream\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:5687:29)
    at setupComponent (C:\Users\Nabil\Project\ream\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:5648:11)
    at renderComponentVNode (C:\Users\Nabil\Project\ream\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:159:17)
    at renderVNode (C:\Users\Nabil\Project\ream\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:235:22)
    at renderVNodeChildren (C:\Users\Nabil\Project\ream\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:250:9)
    at renderVNode (C:\Users\Nabil\Project\ream\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:227:13)
    at renderComponentSubTree (C:\Users\Nabil\Project\ream\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:204:13)
```

**Comment by nblthree** [comment]
There wasn't a problem when I used the local path to ream so I will close this because it's not related to ream
